PROGRAM = fatfs
EXTRA_COMPONENTS = extras/sdio extras/fatfs extras/i2c extras/ds1307
ESPBAUD = 460800

# We provide uint32_t get_fattime() based on the RTC
FATFS_FS_NORTC = 0

include ../../common.mk
